variable "ami" {}
variable "ansible-sg" {}
variable "instance_type" {}
variable "keyname" {}
variable "subnet-id" {}
variable "private_key" {}
variable "HAproxy1" {}
variable "HAproxy2" {}
variable "master1" {}
variable "master2" {}
variable "master3" {}
variable "worker1" {}
variable "worker2" {}
variable "worker3" {}
variable "tag-ansible" {}
variable "bastion_host" {}
variable "vpc_id" {}
variable "tag-ansible-sg" {}